name: Skip DemoApp CI

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

on:
  push:
    branches: '*'
  schedule:
    - cron:  '0 1,7,13,23 * * *'

jobs:
  skip-template-tests:
    runs-on: macos-13
    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check skiptool
        run: swift package --disable-sandbox --allow-writing-to-package-directory skip info

      - name: Build AppDemoKt (SPM)
        run: swift build --jobs 1

      - name: Show Gradle Project Tree
        run: |
          brew install tree
          tree -I build -l .build/plugins/outputs

      - name: Test AppDemoKt (SPM)
        run: swift test --jobs 1

      - name: Show Gradle Build Tree
        run: |
          tree -I build -l .build/plugins/outputs
          ls -lah .build/plugins/outputs/skipapp.swiftpm/AppDemoKtTests/skip-transpiler/AppDemo/.build/AppDemo/outputs/
          ls -lah .build/plugins/outputs/skipapp.swiftpm/AppDemoKtTests/skip-transpiler/AppDemo/.build/AppDemo/outputs/apk/
          ls -lah .build/plugins/outputs/skipapp.swiftpm/AppDemoKtTests/skip-transpiler/AppDemo/.build/AppDemo/outputs/apk/release/AppDemo-release-unsigned.apk

      - name: Test AppDemoKt (Xcode)
        if: false
        run: xcodebuild test -skipPackagePluginValidation -configuration Debug -sdk "macosx" -destination "platform=macosx" -scheme "AppDemoKt"

      - name: Package iOS App
        run: |
          APPNAME="App"
          APPCONFIG="Debug"
          APPPLATFORM="iOS"
          APPSDK="iphoneos"
          APPARTIFACT="${APPNAME}-${APPPLATFORM}-${APPCONFIG}"
          COMMITDATE="$(git log -1 --format=%ad --date=iso-strict ${GITHUB_REF#refs/tags/})"

          xcodebuild archive -jobs 1 -skipPackagePluginValidation -archivePath ".build/${APPARTIFACT}.xcarchive" -configuration "${APPCONFIG}" -scheme 'Demo App' -sdk "${APPSDK}" -destination "generic/platform=${APPPLATFORM}" CODE_SIGNING_ALLOWED=NO || echo "archive failed"

          mkdir -p .build/release/
          cd .build/"${APPARTIFACT}".xcarchive/Products/

          mv "Applications" "Payload"
          tree -h .

          # create the zip file with predictable timestamps
          find "Payload" -exec touch -d "${COMMITDATE:0:19}" {} \;
          ditto -c -k --sequesterRsrc --keepParent "Payload" ../../release/"${APPARTIFACT}.ipa"

          cd ../../release/
          ls -la "${APPARTIFACT}.ipa"
          shasum -a 256 "${APPARTIFACT}.ipa" | tee "${APPARTIFACT}.ipa.sha256"
          cat "${APPARTIFACT}.ipa.sha256" >> releasenotes.txt

      - name: Show PlugIn Output Tree (Xcode)
        run: |
          #tree -I build -l ~/Library/Developer/Xcode/DerivedData/*/SourcePackages/plugins/skipapp.swiftpm.output/AppDemoKt
          tree -I build -l ~/Library/Developer/Xcode/DerivedData/*/SourcePackages/plugins/

